# Generated by Django 5.2.10 on 2026-01-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='days_of_operation',
            field=models.CharField(default='1234567', help_text="Days this route runs (1=Monday, 7=Sunday). E.g., '135' is Mon/Wed/Fri", max_length=7),
        ),
    ]
