# Generated by Django 5.2.10 on 2026-01-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_route_days_of_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
