# Generated by Django 5.2.10 on 2026-02-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_carrier_code_alter_location_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('origin', 'destination', 'carrier', 'departure_time')},
        ),
    ]
