# Generated by Django 5.2.10 on 2026-03-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_route_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='aircraft_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='flight_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
