# Generated by Django 5.2.10 on 2026-03-16 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reportedissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('available_seats', models.IntegerField(blank=True, null=True)),
                ('cabin_class', models.CharField(blank=True, max_length=30)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_instances', to='core.route')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('route', 'date')},
            },
        ),
    ]
